<?php
$MYSQL_HOST = "localhost";
$MYSQL_DATABASE = "kolok1_chat";
$MYSQL_USER = "root";
$MYSQL_PASS = "";
$MYSQL_CHARSET= "utf8mb4";
$MYSQL_OPTIONS = [
    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    PDO::ATTR_EMULATE_PREPARES => false,
];